# Autograd

In [30]:
import torch as t
import numpy as np
from torch.autograd import Variable

## 从Tensor建立

* 设定requires_grad为True，即可自动微分

In [33]:
x = t.ones(2, 2, requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

* 运算后的变量就会拥有grad_fn

In [34]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [35]:
y.grad_fn

* 更复杂的操作

In [49]:
z = y * y *3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


* 使用 .requires_grad_( ... )来改变Tensor的require_grad的标志

In [37]:
a = t.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


## 梯度

* 进行反向传播

In [50]:
out.backward() # out只有一个值所以等于 out.backward(t.tensor(1.))

* 打印 d(out)/dx 的值

In [51]:
print(x.grad)

tensor([[18., 18.],
        [18., 18.]])


In [7]:
y.backward()
x.grad

tensor([[2., 2.],
        [2., 2.]])