In [2]:
import torch as t
import numpy as np

## Tensor构建

* 构建矩阵，不初始化

In [5]:
x = t.empty(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

* 构建矩阵并[0, 1]随机初始化

In [4]:
x = t.rand(5, 3)
x

tensor([[0.1751, 0.3487, 0.3626],
        [0.7004, 0.2946, 0.7998],
        [0.2737, 0.3321, 0.9670],
        [0.6152, 0.0815, 0.9291],
        [0.4720, 0.5820, 0.5015]])

* 构建初值为0，数据类型为torch.long的矩阵

In [6]:
x = t.zeros(5, 3, dtype = t.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

* 从数据构建tensor

In [7]:
x = t.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

* 从存在的tensor创建新的tensor

In [8]:
x = x.new_ones(5, 3, dtype = t.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [11]:
x = t.randn_like(x, dtype = t.float)
x

tensor([[-0.4793, -2.1403,  0.7634],
        [-1.2804, -0.1240, -1.1080],
        [-2.0891,  0.0078,  0.4049],
        [-1.1665,  0.5562,  0.3550],
        [-0.1637,  1.6348,  0.2276]])

* 查看形状

torch.Size是tuple的子类

In [12]:
print(x.size())
# 读取size的两种方法
print('rows: ', x.size()[0])
print('cols: ', x.size()[1])

print('rows: ', x.size(0))
print('cols: ', x.size(1))

torch.Size([5, 3])
rows:  5
cols:  3
rows:  5
cols:  3


## Tensor操作

* 基本加

In [13]:
y = t.rand(5, 3)

In [14]:
# 1.直接加
x + y

tensor([[-0.0490, -1.1488,  1.2458],
        [-1.2412,  0.4439, -0.6034],
        [-1.6940,  0.5119,  1.2681],
        [-0.7365,  1.1159,  1.0303],
        [ 0.5722,  1.8127,  0.2810]])

In [15]:
# 2.torch.add()方法加
t.add(x, y)

tensor([[-0.0490, -1.1488,  1.2458],
        [-1.2412,  0.4439, -0.6034],
        [-1.6940,  0.5119,  1.2681],
        [-0.7365,  1.1159,  1.0303],
        [ 0.5722,  1.8127,  0.2810]])

In [16]:
# 3.指定结果加
result = t.Tensor(5, 3) # 预分配空间
t.add(x, y, out=result)
result

tensor([[-0.0490, -1.1488,  1.2458],
        [-1.2412,  0.4439, -0.6034],
        [-1.6940,  0.5119,  1.2681],
        [-0.7365,  1.1159,  1.0303],
        [ 0.5722,  1.8127,  0.2810]])

* in-place加

In [20]:
print('原本y')
print(y)

print('普通加的y')
y.add(x)
print(y)

print('inplace加的y')
y.add_(x) #add加个_
print(y)

原本y
tensor([[-0.0490, -1.1488,  1.2458],
        [-1.2412,  0.4439, -0.6034],
        [-1.6940,  0.5119,  1.2681],
        [-0.7365,  1.1159,  1.0303],
        [ 0.5722,  1.8127,  0.2810]])
普通加的y
tensor([[-0.0490, -1.1488,  1.2458],
        [-1.2412,  0.4439, -0.6034],
        [-1.6940,  0.5119,  1.2681],
        [-0.7365,  1.1159,  1.0303],
        [ 0.5722,  1.8127,  0.2810]])
inplace加的y
tensor([[-0.5283, -3.2890,  2.0092],
        [-2.5215,  0.3199, -1.7115],
        [-3.7832,  0.5197,  1.6730],
        [-1.9029,  1.6721,  1.3852],
        [ 0.4085,  3.4475,  0.5086]])


* 可以直接使用类似NuumPy的索引方法

In [22]:
y[:, 1]

tensor([-3.2890,  0.3199,  0.5197,  1.6721,  3.4475])

* resize

In [24]:
x = t.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8) # -1代表该大小从其他维度的结果推理
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


* 单个元素tensor获取该元素的值

In [25]:
x = t.randn(1)
print(x)
print(x.item())

tensor([-0.6782])
-0.6781667470932007


## Tensor与NumPy转换

* Tensor -> Numpy

In [16]:
a = t.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [18]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

* Numpy -> Tensor

In [30]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [31]:
b = t.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

* 两者共享内存

In [32]:
b.add_(1)
print(b)
print(a)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]


## 转到GPU

In [26]:
if t.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

* device方法

In [27]:
if t.cuda.is_available():
    device = t.device("cuda")
    y = t.ones_like(x, device = device) # 直接在GPU上创建tensor
    x = x.to(device) # .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", t.double)) # to的同时也可以转换dtype